spring:
  application:
    name: board
  datasource:
    url: jdbc:h2:tcp://localhost/~/projects/Spring-JdbcTemplate-try-it-out/board
    username: sa
    password:
    driver-class-name: org.h2.Driver
  mvc:
    hiddenmethod:
      filter:
        enabled: true

