name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: [ self-hosted, Linux, X64 ]
    steps:
      - name: Hello, World 찍기
        run: echo "Hello, World!"

      - name: 현재 위치 확인하기
        run: |
          pwd
          ls

      # 저장소 코드 체크아웃(현재 해당 리포지토리 코드 가져오기)
      - name: Checkout code
        uses: actions/checkout@v4

      # JDK 세팅 - 이미 세팅되어 있으면, 캐시된 JDK를 사용한다.
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'