name: CI/CD

on:
  push:
    branches:
      - main
      - board/chore/54-CI-CD-도입
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: [ self-hosted, Linux, X64 ]
    steps:
      - name: Hello, World 찍기
        run: echo "Hello, World!"

      # 저장소 코드 체크아웃(현재 해당 리포지토리 코드 가져오기)
      # 풀 리퀘스트/푸쉬에 있는 ID 값을 이용해 해당 리포지토리 코드를 가져온다.
      - name: Checkout code
        uses: actions/checkout@v4

      # JDK 세팅 - 이미 세팅되어 있으면, 캐시된 JDK를 사용한다.
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      # Gradle 캐시 설정
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # gradlew 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Gradle을 사용하여 프로젝트 빌드
      - name: Build with Gradle
        run: ./gradlew clean build