name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: romad-B660M-HDVP-D5-R2-0
    steps:
      - name: Hello, World 찍기
        run: echo "Hello, World!"