name: CI/CD

on:
  push:
    branches:
      - main
      - board/chore/54-CI-CD-도입
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: [ self-hosted, Linux, X64 ]
    steps:
      - name: Hello, World 찍기
        run: echo "Hello, World!"

      # 저장소 코드 체크아웃(현재 해당 리포지토리 코드 가져오기)
      # 풀 리퀘스트/푸쉬에 있는 ID 값을 이용해 해당 리포지토리 코드를 가져온다.
      - name: Checkout code
        uses: actions/checkout@v4

      # JDK 세팅 - 이미 세팅되어 있으면, 캐시된 JDK를 사용한다.
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # gradlew 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Gradle을 사용하여 프로젝트 빌드
      - name: Build with Gradle
        run: ./gradlew clean build

      # Docker를 사용하여 배포
      - name: Deploy with Docker
        env:
          # Docker 이미지 이름 및 태그 설정 (프로젝트에 맞게 수정)
          DOCKER_IMAGE_NAME: "GoGradually/SuperBoard" # 예: myusername/my-spring-app
          # 실행될 Docker 컨테이너 이름 설정
          DOCKER_CONTAINER_NAME: "SuperBoard-instance" # 예: my-spring-app-instance
        run: |
          set -e # 오류 발생 시 즉시 스크립트 중단

          echo "Docker 배포 시작"
          # Docker 이미지 태그
          IMAGE_TAG="latest"

          # 1. Docker 이미지 빌드
          echo "Docker 이미지 빌드: $DOCKER_IMAGE_NAME:$IMAGE_TAG"
          sudo docker build -t $DOCKER_IMAGE_NAME:$IMAGE_TAG .

          # 2. 기존 컨테이너 중지 및 삭제 (같은 이름으로 실행 중인 경우)
          echo "기존 Docker 컨테이너($DOCKER_CONTAINER_NAME) 중지 및 삭제 (존재하는 경우)"
          sudo docker stop $DOCKER_CONTAINER_NAME || true # 실패해도 계속 진행
          sudo docker rm $DOCKER_CONTAINER_NAME || true   # 실패해도 계속 진행

          # 3. 새 Docker 컨테이너 실행
          echo "새 Docker 컨테이너($DOCKER_CONTAINER_NAME) 실행"
          sudo docker run -d -p 8090:8080 --name $DOCKER_CONTAINER_NAME --restart unless-stopped $DOCKER_IMAGE_NAME:$IMAGE_TAG

          echo "오래된 Docker 이미지 정리"
          sudo docker image prune -af || true

          echo "Docker 배포 성공"